<a href="https://colab.research.google.com/github/ogotati/Statistical_Analys_Population_marriage_divorce/blob/main/Population_marriage_divorce.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Завантажуємо всі потрібні бібліотеки для роботи з датасетом.

In [1]:
import numpy as np
import pandas as pd

In [11]:
# Завантажуємо файл та виводимо перші та останні 5 рядків
df = pd.read_csv('/content/dataset_2026-04-22T19_04_27.949862978Z_DEFAULT_INTEGRATION_SSSU_DF_POPULATION_MARRIAGE_DIVORCE_LATEST.csv')
df

/tmp/ipykernel_3054/578674614.py:2: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/dataset_2026-04-22T19_04_27.949862978Z_DEFAULT_INTEGRATION_SSSU_DF_POPULATION_MARRIAGE_DIVORCE_LATEST.csv')

,Показник,Територіальний розріз,Вік,Стать,Тип місцевості,Місяць реєстрації події,Сімейний cтан,Порядок розірвання шлюбу,Громадянство жінки,Громадянство чоловіка,Періодичність,Період,Значення cпостереження,Одиниця виміру,Масштабування,Кількість десяткових знаків,Спеціальне значення даних,Примітки набору даних,Примітки часового ряду,Примітки спостереження
0,Кількість зареєстрованих шлюбів,Україна,60 років і старші,Жінки,Міська,Не застосовується,Загалом,Не застосовується,Усього,Усього,Річна,1989,7974.0,Особа,Одиниці,Нуль,NaN,NaN,"Починаючи з 2014 року, наведено без урахування...",NaN
1,Кількість зареєстрованих шлюбів,Україна,60 років і старші,Жінки,Міська,Не застосовується,Загалом,Не застосовується,Усього,Усього,Річна,1990,7798.0,Особа,Одиниці,Нуль,NaN,NaN,"Починаючи з 2014 року, наведено без урахування...",NaN
2,Кількість зареєстрованих шлюбів,Україна,60 років і старші,Жінки,Міська,Не застосовується,Загалом,Не застосовується,Усього,Усього,Річна,1991,6947.0,Особа,Одиниці,Нуль,NaN,NaN,"Починаючи з 2014 року, наведено без урахування...",NaN
3,Кількість зареєстрованих шлюбів,Україна,60 років і старші,Жінки,Міська,Не застосовується,Загалом,Не застосовується,Усього,Усього,Річна,1992,6109.0,Особа,Одиниці,Нуль,NaN,NaN,"Починаючи з 2014 року, наведено без урахування...",NaN
4,Кількість зареєстрованих шлюбів,Україна,60 років і старші,Жінки,Міська,Не застосовується,Загалом,Не застосовується,Усього,Усього,Річна,1993,6075.0,Особа,Одиниці,Нуль,NaN,NaN,"Починаючи з 2014 року, наведено без урахування...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
700533,Загальний коефіцієнт розлучуваності,Житомирська,Не застосовується,Не застосовується,Загалом,Не застосовується,Не застосовується,Не застосовується,Усього,Усього,Річна,2017,3.1,На 1000 осіб наявного населення,Одиниці,Один,NaN,NaN,NaN,NaN
700534,Загальний коефіцієнт розлучуваності,Житомирська,Не застосовується,Не застосовується,Загалом,Не застосовується,Не застосовується,Не застосовується,Усього,Усього,Річна,2018,3.9,На 1000 осіб наявного населення,Одиниці,Один,NaN,NaN,NaN,NaN
700535,Загальний коефіцієнт розлучуваності,Житомирська,Не застосовується,Не застосовується,Загалом,Не застосовується,Не застосовується,Не застосовується,Усього,Усього,Річна,2019,3.6,На 1000 осіб наявного населення,Одиниці,Один,NaN,NaN,NaN,NaN
700536,Загальний коефіцієнт розлучуваності,Житомирська,Не застосовується,Не застосовується,Загалом,Не застосовується,Не застосовується,Не застосовується,Усього,Усього,Річна,2020,3.0,На 1000 осіб наявного населення,Одиниці,Один,NaN,NaN,NaN,NaN
700537,Загальний коефіцієнт розлучуваності,Житомирська,Не застосовується,Не застосовується,Загалом,Не застосовується,Не застосовується,Не застосовується,Усього,Усього,Річна,2021,3.2,На 1000 осіб наявного населення,Одиниці,Один,NaN,NaN,NaN,NaN

In [12]:
# Інформація про тип даних і кількість записів
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700538 entries, 0 to 700537
Data columns (total 20 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Показник                     700538 non-null  object
 1   Територіальний розріз        700538 non-null  object
 2   Вік                          700538 non-null  object
 3   Стать                        700538 non-null  object
 4   Тип місцевості               700538 non-null  object
 5   Місяць реєстрації події      700538 non-null  object
 6   Сімейний cтан                700538 non-null  object
 7   Порядок розірвання шлюбу     700538 non-null  object
 8   Громадянство жінки           700538 non-null  object
 9   Громадянство чоловіка        700538 non-null  object
 10  Періодичність                700538 non-null  object
 11  Період                       700538 non-null  int64
 12  Значення cпостереження       71837 non-null   float64
 13  Одиниця виміру               700538 non-null  object
 14  Масштабування                700538 non-null  object
 15  Кількість десяткових знаків  700538 non-null  object
 16  Спеціальне значення даних    627645 non-null  object
 17  Примітки набору даних        0 non-null       float64
 18  Примітки часового ряду       665005 non-null  object
 19  Примітки спостереження       1260 non-null    object
dtypes: float64(2), int64(1), object(17)
memory usage: 106.9+ MB

In [13]:
# Аналіз головних статистичних показників
df.describe()

              Період  Значення cпостереження  Примітки набору даних
count  700538.000000            71837.000000                    0.0
mean     2011.636619             4629.858401                    NaN
std         5.969786            24296.802111                    NaN
min      1989.000000                0.500000                    NaN
25%      2007.000000                5.000000                    NaN
50%      2012.000000               83.000000                    NaN
75%      2017.000000             1387.000000                    NaN
max      2021.000000           493067.000000                    NaN

In [14]:
# Виводимо назви стовпців
df.columns

Index(['Показник', 'Територіальний розріз', 'Вік', 'Стать', 'Тип місцевості',
       'Місяць реєстрації події', 'Сімейний cтан', 'Порядок розірвання шлюбу',
       'Громадянство жінки', 'Громадянство чоловіка', 'Періодичність',
       'Період', 'Значення cпостереження', 'Одиниця виміру', 'Масштабування',
       'Кількість десяткових знаків', 'Спеціальне значення даних',
       'Примітки набору даних', 'Примітки часового ряду',
       'Примітки спостереження'],
      dtype='object')

In [15]:
# Кількість унікальних значень у кожному стовпці
print(df.nunique())

Показник                           6
Територіальний розріз             28
Вік                               12
Стать                              3
Тип місцевості                     3
Місяць реєстрації події           13
Сімейний cтан                      5
Порядок розірвання шлюбу           5
Громадянство жінки               177
Громадянство чоловіка             65
Періодичність                      1
Період                            33
Значення cпостереження         12435
Одиниця виміру                     4
Масштабування                      1
Кількість десяткових знаків        3
Спеціальне значення даних          1
Примітки набору даних              0
Примітки часового ряду            13
Примітки спостереження             4
dtype: int64

In [16]:
# Перегляд унікальних значень для ключових стовпців, щоб визначити яку інформацію (шум) можна прибрати і яку обробити
cols_to_check = ['Показник', 'Територіальний розріз', 'Вік', 'Стать', 'Тип місцевості',
       'Місяць реєстрації події', 'Сімейний cтан', 'Порядок розірвання шлюбу', 'Періодичність',
       'Період', 'Одиниця виміру', 'Масштабування',
       'Кількість десяткових знаків', 'Спеціальне значення даних',
       'Примітки набору даних', 'Примітки часового ряду',
       'Примітки спостереження']

for col in cols_to_check:
    print(f"🔹 {col}:")
    print(df[col].unique())
    print("-" * 30)

🔹 Показник:
['Кількість зареєстрованих шлюбів'
 'Середній вік чоловіків та жінок, які зареєстрували шлюб'
 'Медіанний вік чоловіків та жінок, які зареєстрували шлюб'
 'Кількість розірвань шлюбів' 'Загальний коефіцієнт шлюбності'
 'Загальний коефіцієнт розлучуваності']
------------------------------
🔹 Територіальний розріз:
['Україна' 'Вінницька' 'Волинська' 'Дніпропетровська'
 'Автономна Республіка Крим' 'Донецька' 'Івано-Франківська' 'Запорізька'
 'Житомирська' 'Закарпатська' 'Київська' 'Львівська' 'Луганська'
 'Кіровоградська' 'Миколаївська' 'Полтавська' 'Одеська' 'Рівненська'
 'Тернопільська' 'Харківська' 'Херсонська' 'Сумська' 'Чернігівська'
 'Черкаська' 'Чернівецька' 'Хмельницька' 'Севастополь' 'Київ']
------------------------------
🔹 Вік:
['60 років і старші' '30-34 роки' '55-59 років' '45-49 років'
 '35-39 років' '50-54 роки' 'До 25 років' 'Не застосовується' '40-44 роки'
 '25-29 років' 'До 20 років' '20-24 роки']
------------------------------
🔹 Стать:
['Жінки' 'Чоловіки' 'Не застосовується']
------------------------------
🔹 Тип місцевості:
['Міська' 'Сільська' 'Загалом']
------------------------------
🔹 Місяць реєстрації події:
['Не застосовується' 'Лютий' 'Квітень' 'Січень' 'Червень' 'Грудень'
 'Серпень' 'Травень' 'Липень' 'Вересень' 'Березень' 'Листопад' 'Жовтень']
------------------------------
🔹 Сімейний cтан:
['Загалом' 'Ніколи не перебували у шлюбі' 'Розлучені' 'Удівці (удови)'
 'Не застосовується']
------------------------------
🔹 Порядок розірвання шлюбу:
['Не застосовується'
 'Зареєстровано в органах державної реєстрації актів цивільного стану'
 'Розглянуто судами першої інстанції справ про розірвання шлюбу позовного провадження із задоволенням позову'
 'Загалом'
 'Розглянуто судами першої інстанції справ про розірвання шлюбу окремого провадження із задоволенням заяви']
------------------------------
🔹 Періодичність:
['Річна']
------------------------------
🔹 Період:
[1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002
 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016
 2017 2018 2019 2020 2021]
------------------------------
🔹 Одиниця виміру:
['Особа' 'Одиниця' 'Рік' 'На 1000 осіб наявного населення']
------------------------------
🔹 Масштабування:
['Одиниці']
------------------------------
🔹 Кількість десяткових знаків:
['Нуль' 'Два' 'Один']
------------------------------
🔹 Спеціальне значення даних:
[nan 'Явищ не було']
------------------------------
🔹 Примітки набору даних:
[nan]
------------------------------
🔹 Примітки часового ряду:
['Починаючи з 2014 року, наведено без урахування тимчасово окупованої території Автономної Республіки Крим, м. Севастополя та частини тимчасово окупованих територій у Донецькій та Луганській областях.'
 nan
 'Починаючи з 2014 року, наведено без урахування частини тимчасово окупованих територій у Донецькій області.'
 'Починаючи з 2014 року, наведено без урахування частини тимчасово окупованих територій у Луганській області.'
 'Починаючи з 2014 року, розраховано без урахування тимчасово окупованої території Автономної Республіки Крим, м. Севастополя та частини тимчасово окупованих територій у Донецькій та Луганській областях.'
 'Починаючи з 2014 року, розраховано без урахування частини тимчасово окупованих територій у Донецькій області.'
 'Починаючи з 2014 року, розраховано без урахування частини тимчасово окупованих територій у Луганській області.'
 'За даними Державної судової адміністрації України.'
 '1. Починаючи з 2014 року, наведено без урахування тимчасово окупованої території Автономної Республіки Крим, м. Севастополя та частини тимчасово окупованих територій у Донецькій та Луганській областях. 2. За даними Державної судової адміністрації України.'
 '1. Починаючи з 2014 року, наведено без урахування частини тимчасово окупованих територій у Луганській області. 2. За даними Державної судової адміністрації України.'
 '1. Починаючи з 2014 року, наведено без урахування частини тимчасово окупованих територій у Донецькій області. 2. За даними Державної судової адміністрації України.'
 'За 2014 рік розраховано без урахування тимчасово окупованої території Автономної Республіки Крим, м. Севастополя та частини тимчасово окупованих територій у Донецькій та Луганській областях. Починаючи з 2015 року - розраховано без урахування тимчасово окупованої території Автономної Республіки Крим, м. Севастополя та відповідних даних по Донецькій та Луганській областях.'
 'Починаючи з 2014 року, здійснення розрахунків є некоректним у зв’язку з відсутністю інформації по частині тимчасово окупованих територій у Донецькій області.'
 'Починаючи з 2014 року, здійснення розрахунків є некоректним у зв’язку з відсутністю інформації по частині тимчасово окупованих територій у Луганській області.']
------------------------------
🔹 Примітки спостереження:
[nan
 'Включаючи м. Севастополь та територію, яка була підпорядкована Севастопольській міськраді.'
 'Інформація відсутня.'
 'Дані включено до даних по Автономній Республіці Крим.'
 'За даними органів державної реєстрації актів цивільного стану без урахування розірвань шлюбів, здійснених у судовому порядку.']
------------------------------

In [20]:
# Переводимо стовпчик Місяць реєстрації та Період у формат дати щоб будувати часові ряди
# Словник українських місяців
month_map = {
    'Січень': '01', 'Лютий': '02', 'Березень': '03',
    'Квітень': '04', 'Травень': '05', 'Червень': '06',
    'Липень': '07', 'Серпень': '08', 'Вересень': '09',
    'Жовтень': '10', 'Листопад': '11', 'Грудень': '12',
    'Не застосовується': 'None'
}

In [23]:
#  Замінюємо назви місяців на цифри
df['month_num'] = df['Місяць реєстрації події'].map(month_map)

# Створюємо строкову колонку формату "РІК-МІСЯЦЬ-01"
df['temp_date_str'] = df['Період'].astype(str) + '-' + df['month_num'] + '-01'

# Конвертуємо у формат datetime
df['Початок періоду'] = pd.to_datetime(df['temp_date_str'], errors='coerce')

# Видаляємо допоміжні колонки
df = df.drop(columns=['month_num', 'temp_date_str'])

df

/tmp/ipykernel_3054/1514219691.py:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Початок періоду'] = pd.to_datetime(df['temp_date_str'], errors='coerce')

,Показник,Територіальний розріз,Вік,Стать,Тип місцевості,Місяць реєстрації події,Сімейний cтан,Порядок розірвання шлюбу,Громадянство жінки,Громадянство чоловіка,...,Період,Значення cпостереження,Одиниця виміру,Масштабування,Кількість десяткових знаків,Спеціальне значення даних,Примітки набору даних,Примітки часового ряду,Примітки спостереження,Початок періоду
0,Кількість зареєстрованих шлюбів,Україна,60 років і старші,Жінки,Міська,Не застосовується,Загалом,Не застосовується,Усього,Усього,...,1989,7974.0,Особа,Одиниці,Нуль,NaN,NaN,"Починаючи з 2014 року, наведено без урахування...",NaN,NaT
1,Кількість зареєстрованих шлюбів,Україна,60 років і старші,Жінки,Міська,Не застосовується,Загалом,Не застосовується,Усього,Усього,...,1990,7798.0,Особа,Одиниці,Нуль,NaN,NaN,"Починаючи з 2014 року, наведено без урахування...",NaN,NaT
2,Кількість зареєстрованих шлюбів,Україна,60 років і старші,Жінки,Міська,Не застосовується,Загалом,Не застосовується,Усього,Усього,...,1991,6947.0,Особа,Одиниці,Нуль,NaN,NaN,"Починаючи з 2014 року, наведено без урахування...",NaN,NaT
3,Кількість зареєстрованих шлюбів,Україна,60 років і старші,Жінки,Міська,Не застосовується,Загалом,Не застосовується,Усього,Усього,...,1992,6109.0,Особа,Одиниці,Нуль,NaN,NaN,"Починаючи з 2014 року, наведено без урахування...",NaN,NaT
4,Кількість зареєстрованих шлюбів,Україна,60 років і старші,Жінки,Міська,Не застосовується,Загалом,Не застосовується,Усього,Усього,...,1993,6075.0,Особа,Одиниці,Нуль,NaN,NaN,"Починаючи з 2014 року, наведено без урахування...",NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
700533,Загальний коефіцієнт розлучуваності,Житомирська,Не застосовується,Не застосовується,Загалом,Не застосовується,Не застосовується,Не застосовується,Усього,Усього,...,2017,3.1,На 1000 осіб наявного населення,Одиниці,Один,NaN,NaN,NaN,NaN,NaT
700534,Загальний коефіцієнт розлучуваності,Житомирська,Не застосовується,Не застосовується,Загалом,Не застосовується,Не застосовується,Не застосовується,Усього,Усього,...,2018,3.9,На 1000 осіб наявного населення,Одиниці,Один,NaN,NaN,NaN,NaN,NaT
700535,Загальний коефіцієнт розлучуваності,Житомирська,Не застосовується,Не застосовується,Загалом,Не застосовується,Не застосовується,Не застосовується,Усього,Усього,...,2019,3.6,На 1000 осіб наявного населення,Одиниці,Один,NaN,NaN,NaN,NaN,NaT
700536,Загальний коефіцієнт розлучуваності,Житомирська,Не застосовується,Не застосовується,Загалом,Не застосовується,Не застосовується,Не застосовується,Усього,Усього,...,2020,3.0,На 1000 осіб наявного населення,Одиниці,Один,NaN,NaN,NaN,NaN,NaT
700537,Загальний коефіцієнт розлучуваності,Житомирська,Не застосовується,Не застосовується,Загалом,Не застосовується,Не застосовується,Не застосовується,Усього,Усього,...,2021,3.2,На 1000 осіб наявного населення,Одиниці,Один,NaN,NaN,NaN,NaN,NaT

In [24]:
print(df['Початок періоду'].dtype)

datetime64[ns]

Очищення датасету від "шумових" колонок, які не несуть аналітичної цінності

In [25]:
# Список колонок для видалення
cols_to_remove = [
    'Періодичність',
    'Масштабування',
    'Кількість десяткових знаків',
     'Примітки набору даних', 'Примітки часового ряду', 'Примітки спостереження'
]

df = df.drop(columns=[c for c in cols_to_remove if c in df.columns])

# Перевіряємо результат
print("Залишилися колонки:", df.columns.tolist())

Залишилися колонки: ['Показник', 'Територіальний розріз', 'Вік', 'Стать', 'Тип місцевості', 'Місяць реєстрації події', 'Сімейний cтан', 'Порядок розірвання шлюбу', 'Громадянство жінки', 'Громадянство чоловіка', 'Період', 'Значення cпостереження', 'Одиниця виміру', 'Спеціальне значення даних', 'Початок періоду']

Також видаляємо рядки для стовпчику "Спеціальне значення даних" з атрибутом "Явищ не було"

In [26]:
df = df[df['Спеціальне значення даних'] != 'Явищ не було']

# Після цього видаляємо сам стовпець, бо він став порожнім
df = df.drop(columns=['Спеціальне значення даних'])

print(f"Залишилося рядків: {len(df)}")

Залишилося рядків: 72893

In [27]:
df.columns

Index(['Показник', 'Територіальний розріз', 'Вік', 'Стать', 'Тип місцевості',
       'Місяць реєстрації події', 'Сімейний cтан', 'Порядок розірвання шлюбу',
       'Громадянство жінки', 'Громадянство чоловіка', 'Період',
       'Значення cпостереження', 'Одиниця виміру', 'Початок періоду'],
      dtype='object')

Так як всі числові дані розміщені у одному стовпці і розшифровка розмірності знаходиться в іншому стовпці розкладаємо "перемішані" числа з одного стовпця у три окремі нові колонки, базуючись на умовах у сусідній колонці.

In [28]:
# 1. Створюємо стовпчик "Кількість"
# Якщо Одиниця виміру — це Особа АБО Одиниця, копіюємо число, інакше — порожньо (NaN)
df['Кількість'] = np.where(
    df['Одиниця виміру'].isin(['Особа', 'Одиниця']),
    df['Значення cпостереження'],
    np.nan
)

# 2. Створюємо стовпчик "Вік_показник"
# Якщо Одиниця виміру — це Рік, копіюємо число
df['Вік_показник'] = np.where(
    df['Одиниця виміру'] == 'Рік',
    df['Значення cпостереження'],
    np.nan
)

# 3. Створюємо стовпчик "Коефіцієнт на 1000 осіб"
# Якщо Одиниця виміру — це відповідний текст, копіюємо число
df['Коефіцієнт на 1000 осіб'] = np.where(
    df['Одиниця виміру'] == 'На 1000 осіб наявного населення',
    df['Значення cпостереження'],
    np.nan
)

# Перевіряємо результат
print(df[['Одиниця виміру', 'Значення cпостереження', 'Кількість', 'Вік_показник', 'Коефіцієнт на 1000 осіб']].head(20))

   Одиниця виміру  Значення cпостереження  Кількість  Вік_показник  \
0           Особа                  7974.0     7974.0           NaN
1           Особа                  7798.0     7798.0           NaN
2           Особа                  6947.0     6947.0           NaN
3           Особа                  6109.0     6109.0           NaN
4           Особа                  6075.0     6075.0           NaN
5           Особа                  5309.0     5309.0           NaN
6           Особа                  4589.0     4589.0           NaN
7           Особа                  4253.0     4253.0           NaN
8           Особа                  5103.0     5103.0           NaN
9           Особа                  4973.0     4973.0           NaN
10          Особа                  5182.0     5182.0           NaN
11          Особа                  5433.0     5433.0           NaN
12          Особа                  5114.0     5114.0           NaN
13          Особа                  4735.0     4735.0           NaN
14          Особа                  4873.0     4873.0           NaN
15          Особа                  4788.0     4788.0           NaN
16          Особа                  4241.0     4241.0           NaN
17          Особа                  3876.0     3876.0           NaN
18          Особа                  3720.0     3720.0           NaN
19          Особа                  3806.0     3806.0           NaN

    Коефіцієнт на 1000 осіб
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN
5                       NaN
6                       NaN
7                       NaN
8                       NaN
9                       NaN
10                      NaN
11                      NaN
12                      NaN
13                      NaN
14                      NaN
15                      NaN
16                      NaN
17                      NaN
18                      NaN
19                      NaN

In [29]:
print(f"Кількість рядків: {df_final.shape[0]}")
print(f"Кількість колонок: {df_final.shape[1]}")
print("\nТипи даних:")
print(df_final.dtypes)

NameError: name 'df_final' is not defined

In [31]:
final_columns = [
    'Показник', 'Територіальний розріз', 'Вік', 'Стать',
    'Тип місцевості', 'Місяць реєстрації події', 'Сімейний cтан',
    'Порядок розірвання шлюбу', 'Громадянство жінки',
    'Громадянство чоловіка', 'Період', 'Початок періоду',
    'Кількість', 'Вік_показник', 'Коефіцієнт на 1000 осіб', 'Значення cпостереження'
]
df_for_tableau = df[[c for c in final_columns if c in df.columns]]
df_for_tableau

,Показник,Територіальний розріз,Вік,Стать,Тип місцевості,Місяць реєстрації події,Сімейний cтан,Порядок розірвання шлюбу,Громадянство жінки,Громадянство чоловіка,Період,Початок періоду,Кількість,Вік_показник,Коефіцієнт на 1000 осіб,Значення cпостереження
0,Кількість зареєстрованих шлюбів,Україна,60 років і старші,Жінки,Міська,Не застосовується,Загалом,Не застосовується,Усього,Усього,1989,NaT,7974.0,NaN,NaN,7974.0
1,Кількість зареєстрованих шлюбів,Україна,60 років і старші,Жінки,Міська,Не застосовується,Загалом,Не застосовується,Усього,Усього,1990,NaT,7798.0,NaN,NaN,7798.0
2,Кількість зареєстрованих шлюбів,Україна,60 років і старші,Жінки,Міська,Не застосовується,Загалом,Не застосовується,Усього,Усього,1991,NaT,6947.0,NaN,NaN,6947.0
3,Кількість зареєстрованих шлюбів,Україна,60 років і старші,Жінки,Міська,Не застосовується,Загалом,Не застосовується,Усього,Усього,1992,NaT,6109.0,NaN,NaN,6109.0
4,Кількість зареєстрованих шлюбів,Україна,60 років і старші,Жінки,Міська,Не застосовується,Загалом,Не застосовується,Усього,Усього,1993,NaT,6075.0,NaN,NaN,6075.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
700533,Загальний коефіцієнт розлучуваності,Житомирська,Не застосовується,Не застосовується,Загалом,Не застосовується,Не застосовується,Не застосовується,Усього,Усього,2017,NaT,NaN,NaN,3.1,3.1
700534,Загальний коефіцієнт розлучуваності,Житомирська,Не застосовується,Не застосовується,Загалом,Не застосовується,Не застосовується,Не застосовується,Усього,Усього,2018,NaT,NaN,NaN,3.9,3.9
700535,Загальний коефіцієнт розлучуваності,Житомирська,Не застосовується,Не застосовується,Загалом,Не застосовується,Не застосовується,Не застосовується,Усього,Усього,2019,NaT,NaN,NaN,3.6,3.6
700536,Загальний коефіцієнт розлучуваності,Житомирська,Не застосовується,Не застосовується,Загалом,Не застосовується,Не застосовується,Не застосовується,Усього,Усього,2020,NaT,NaN,NaN,3.0,3.0
700537,Загальний коефіцієнт розлучуваності,Житомирська,Не застосовується,Не застосовується,Загалом,Не застосовується,Не застосовується,Не застосовується,Усього,Усього,2021,NaT,NaN,NaN,3.2,3.2

Вивантажуємо файл для подальшої роботи

In [32]:
from google.colab import files

file_name = 'data_for_tableau_long.csv'

# Зберігаємо з utf-8-sig для коректного відображення кирилиці в Tableau та Excel
df_for_tableau.to_csv(file_name, index=False, encoding='utf-8-sig')

# Завантажуємо на комп'ютер
files.download(file_name)